### ISSUE TITLE
Issue with Apple Silicon Processor 

### ISSUE THREAD

**Issue by hjo33** [jnr/jffi#119]
It seams like the file expects an arm64 file:
.... (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e'))

```
java.lang.UnsatisfiedLinkError: /private/var/folders/7_/21jkw_sd29n37lpnnpm22vpm0000gn/T/jffi1706266907387692424.dylib: dlopen(/private/var/folders/7_/21jkw_sd29n37lpnnpm22vpm0000gn/T/jffi1706266907387692424.dylib, 0x0001): tried: '/private/var/folders/7_/21jkw_sd29n37lpnnpm22vpm0000gn/T/jffi1706266907387692424.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/jffi1706266907387692424.dylib' (no such file)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.kenai.jffi.internal.StubLoader.loadFromJar(StubLoader.java:371)
	at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:258)
	at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:444)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.kenai.jffi.Init.load(Init.java:68)
	at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:49)
	at com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:45)
	at com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
	at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
	at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
	at com.kenai.jffi.Type.resolveSize(Type.java:155)
	at com.kenai.jffi.Type.size(Type.java:138)
	at jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:187)
	at jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
	at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:66)
	at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:41)
	at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:62)
	at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:58)
	at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
```

Java Version:
```
openjdk version "11.0.13" 2021-10-19 LTS
OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.52+13-CA (build 11.0.13+8-LTS, mixed mode)
```

I don't know how to react to this issue

**Comment by headius** [comment]
More recent versions of jffi do support Apple Silicon, albeit without varargs support. What version of jffi is in use here?

**Comment by hjo33** [comment]
Well it seems like the project itself does not use jiffi at all. 
It seems to throw a missing link exception while building with maven.
This occurs directly in the java folder I guess so.

`[ERROR] java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/java/libjffi-1.2.dylib
[ERROR] 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
[ERROR] 	at java.base/java.lang.Runtime.load0(Runtime.java:768)
[ERROR] 	at java.base/java.lang.System.load(System.java:1837)
[ERROR] 	at com.kenai.jffi.internal.StubLoader.loadFromBootPath(StubLoader.java:316)
[ERROR] 	at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:249)
[ERROR] 	at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:434)
[ERROR] 	at java.base/java.lang.Class.forName0(Native Method)
[ERROR] 	at java.base/java.lang.Class.forName(Class.java:398)
[ERROR] 	at com.kenai.jffi.Init.load(Init.java:68)`

This is not the only one unsatisfied Link error...

Any suggestions to work around this problem

**Comment by headius** [comment]
I can't tell what you are running to cause this error. Is this happening inside some application? Please provide information on how to reproduce, what platform you are on (Java and OS), etc please.

**Comment by headius** [comment]
Additional support for M1 was released a few weeks ago. Please reopen or file a new issue if you continue to have problems.
